# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: reddit_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tajne

  adminer:
    image: adminer
    restart: always
    ports:
      - 5432:5433